#!/bin/bash
#Made by Gregoryx12 aka TheShadowFog
#if you want to use the GTK version. Run todogtk.sh
#Thanks to the many people on stack overflow. :P
#Edit below

#basename $0
#file=~/basename $0.txt
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#if [ -z "${EDITOR+xxx}" ]; then echo VAR is not set at all; fi
#if [ -z "${VISUAL+xxx}" ]; then echo VAR is not set at all; fi
var_defined() {
    local var_name=$1
    set | grep "^${var_name}=" 1>/dev/null
    return $?
}

if [ -f ~/$BASH_SOURCE.txt ]
then
echo exists >> /dev/null 2>&1
else
touch ~/$BASH_SOURCE.txt
fi

case "$1" in
 
 edit)
#if [ -z "${EDITOR+xxx}" ]; then echo VAR is not set at all; fi
if var_defined VISUAL; then
$VISUAL ~/$BASH_SOURCE.txt
else
    echo "VISUAL is not defined"
fi

if var_defined EDITOR; then
$EDITOR ~/$BASH_SOURCE.txt
else
    echo "EDITOR is not defined"
fi


nano ~/$BASH_SOURCE.txt
        exit  
	;;
   view)
if var_defined VISUAL; then
$VISUAL ~/$BASH_SOURCE.txt
else
    echo "VISUAL is not defined"
fi

if var_defined EDITOR; then
$EDITOR ~/$BASH_SOURCE.txt
else
    echo "EDITOR is not defined"
fi

        exit  
        ;;

  clear)
     > ~/$BASH_SOURCE.txt
     exit
    ;;

    add)    
echo "$2" >> ~/$BASH_SOURCE.txt
   exit
  ;;


    info)
    echo "theshadowfog.com"
     exit
    ;;


  help)
   echo "You may run: "
    echo "./todo.sh view"
    echo "./todo.sh edit"
    echo "./todo.sh clear"
    echo "./todo.sh help"
    echo "./todo.sh info" 
    echo "Please use quotes when you use the add command."
   exit
    ;;


esac
#exit 0


#if [ ! -s $file ]; then
#echo "$file is empty"
#else
#echo "Your current todo.txt"
#cat $file
#nl $file
#fi

#if [ -f $file ]
#then
#echo exists >> /dev/null 2>&1
#else
#touch $file
#fi

while :
do
echo "What would you like to add to your todo list?"
read todotext
echo $todotext >> ~/$BASH_SOURCE.txt

echo "Do you want to add anything else?"
read yesorno
addmore=$yesorno

if [ "${yesorno^^*}" == "YES" ]; then
echo "Ok"  >> /dev/null 2>&1
#read todotext 
#echo $todotext >> todo.txt
  elif [ "${yesorno^^*}" == "NO" ]; then
exit
else
exit
  fi

done


