#!/bin/bash
# Copyright (C) 2011 TheShadowFog
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

    
#Made by Gregoryx12 aka TheShadowFog
#if you want to use the GTK version. Run todogtk.sh
#Thanks to the many people on stack overflow. :P
#Edit below

#basename $0
#file=~/basename $0.txt
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#if [ -z "${EDITOR+xxx}" ]; then echo VAR is not set at all; fi
#if [ -z "${VISUAL+xxx}" ]; then echo VAR is not set at all; fi
file=$(basename $BASH_SOURCE)

var_defined() {
    local var_name=$1
    set | grep "^${var_name}=" 1>/dev/null
    return $?
}

if [ -f ~/$file.txt ]
then
    echo exists >> /dev/null 2>&1
else
    touch ~/$file.txt
fi

case "$1" in
 
 edit)
#if [ -z "${EDITOR+xxx}" ]; then echo VAR is not set at all; fi
if var_defined VISUAL; then
    $VISUAL ~/$file.txt
else
    echo "VISUAL is not defined"
fi

if var_defined EDITOR; then
    $EDITOR ~/$file.txt
else
    echo "EDITOR is not defined" >> /dev/null 2>&1
fi


        exit
;;
   view)
#if var_defined VISUAL; then
   # cat ~/$file.txt
#else
#    echo "VISUAL is not defined"
#fi
cat ~/$file.txt

#if var_defined EDITOR; then
#    $EDITOR ~/$file.txt
#else
#    echo "EDITOR is not defined"
#fi

exit
        ;;

  clear)
     > ~/$file.txt
     exit
    ;;

    "")
    echo "todo view"
    echo "todo edit"
    echo "todo clear"
    echo "todo help"
    echo "todo info"
    echo "Please use quotes when you use the add command."
   exit
    ;;

    add)
echo "$2" >> ~/$file.txt
   exit
  ;;


    info)
    echo "theshadowfog.com"
     exit
    ;;


  help)
   echo "You may run: "
    echo "./todo.sh view"
    echo "./todo.sh edit"
    echo "./todo.sh clear"
    echo "./todo.sh help"
    echo "./todo.sh info"
    echo "Please use quotes when you use the add command."
   exit
    ;;


esac
#exit 0
